### ISSUE TITLE
[10.0] Google Maps JavaScript API warning: RetiredVersion

### ISSUE THREAD

**Issue by BT-aestebanez** [gityopie/odoo-addons#102]
Hello,

I think you already fixed it for v12.0. Are you going to backport the code?

Thanks,
Alvaro

**Comment by gityopie** [comment]
Hi @BT-aestebanez 

On version 11.0 and 12.0, I have updated the google maps source by use the `quarterly channel` instead of version number.

I don't have plan to back port the code to version <=10.0

**Comment by BT-aestebanez** [comment]
Thanks for the information.

You can close the issue then
