### ISSUE TITLE
[12.0] Conflict with partner_autocomplete

### ISSUE THREAD

**Issue by katyukha** [gityopie/odoo-addons#104]
Hi!

Great addon, but we have following conflict on Odoo 12.0

In case when both addons (`sale_maps` and `partner_autocomplete`) installed, last addon that was installed override widget of previous addon placed on `name` field of partner.

Steps to reproduce:
1. Install `sales_maps` addon
2. Open form to create new contact
3. Choos type of contact: Company
4. Start typing company name, and see that autocomplete address is working
5. Install `partner_autocomplete` addon
6. Reload page
7. Open contact creation form
8. Choose contact type Company
9. Start typing company name
10. Choose company from drop-down menu
11. See that company logo changed, but address not completed
12. Choose contact type Individual
13. Start typing contact name
14. Nothing happens.

**Comment by gityopie** [comment]
Hi @katyukha,

Thanks for playing the module.
Yes, installing `partner_autocomplete` after the `sale_maps` is installed will overwrite the widget.
if you want to use name autocomplete from `partner_autocomplete` and address autocomplete from `sale_maps`, yes you can have both.

but if you installed `base_address_extended` addon too after `sale_maps` addon, the address autocomplete will gone.

**Comment by katyukha** [comment]
Thank you for response
