### ISSUE TITLE
[12.0] Country & state Canada or completely different

### ISSUE THREAD

**Issue by CasVissers** [gityopie/odoo-addons#105]
Hi,

For most contacts I get: 
Country = Canada
State = New Brunswick
For all contact the country or country is never correct. In the Netherlands we don't use states.

All other information is correct. Any idea why this is happening?

With kind regards,
Cas

**Comment by gityopie** [comment]
Hi @CasVissers 

have you try localize the map?
You can find the settings on `Settings > General Settings: Google Map View`
![Screen Shot 2019-04-30 at 6 08 49 AM](https://user-images.githubusercontent.com/3539144/56932599-9bda4d00-6b0e-11e9-947e-13aa5b5ae68a.png)

**Comment by CasVissers** [comment]
@gityopie 
Thanks for your answer. I tried it just now, but no change.

**Comment by CasVissers** [comment]
@gityopie 
It might be because Geocoding, Maps Static, Maps Javascript are not activated. Only gplaces autocomplete is. Will check this.

**Comment by gityopie** [comment]
@CasVissers could you send me an address? so I can check.

**Comment by CasVissers** [comment]
@gityopie 
I only have it with Dutch companies (autocomplete function). German/Italy tested and worked.

Example company: Philips Medical Systems International B.V.

**Comment by CasVissers** [comment]
@gityopie 
After installing l10n_nl_country_states it started working. Closing issue as resolved for me.

**Comment by CasVissers** [comment]
@gityopie 
I have another question, Odoo is not very strong in decoding street names:
When entering street = The Lane 303
Odoo makes street_name = The and street_number the Lane 303.

In web google maps we always write in the field street, would be an option to write in street_name  and street_number fields?

**Comment by gityopie** [comment]
@CasVissers 
Unfortunately, the current implement for the Google autocomplete widget does not support this yet.
Will need to develop a new module as the `street_number` fields was defined not on `base` module but `base_address_extend` module

**Comment by CasVissers** [comment]
@gityopie 
Do you have plans to build this extension?

**Comment by gityopie** [comment]
@CasVissers I'll check, will came back to you later if can build the module or not (probably this weekend)
would be great if you open a new issue as this one is already closed. Thanks
