### ISSUE TITLE
[web_google_maps] Wrong state and country (gplaces_autocomplete.js)

### ISSUE THREAD

**Issue by BT-aestebanez** [gityopie/odoo-addons#112]
First of all we would like to thank for your work, the module is nice

We have this issue in 12.0 (maybe other versions are affected too)

If you install several localisations, several states are loaded, some of them sharing the same code:
![image](https://user-images.githubusercontent.com/13062286/64764684-ea7b0780-d542-11e9-8c8b-924b96ea7374.png)

Image taken from odoo runbot

After debugging the code we realized that the search_read() called by JS tries to find the state by code, finding several records and getting the first one to fill the state. This is in most cases wrong, and the change of the state changes as well (onchange) the country.

The solution would be to send not only the state code, but also the country.

Thanks for your help
Alvaro

**Comment by gityopie** [comment]
Hi @BT-aestebanez 

Thanks for your feedback.
I've created a new branch 12.0-dev and opened a PR #113 
could you please take a look?
please let me know if it's solved the issue or not

Thank you!

**Comment by BT-aestebanez** [comment]
Hi @gityopie 
I guess we can close this issue
because this code https://github.com/gityopie/odoo-addons/pull/113 fixes it

Thanks for your work
Alvaro
