### ISSUE TITLE
Number of Places API call is extreme

### ISSUE THREAD

**Issue by mlamie** [gityopie/odoo-addons#120]
Hi Yopi Angi we do use all your Odoo modules in Odoo v12 EE and it does work very well. There is only one downside, the number of "Google Places API" calls is extreme.

The following counters in Google Cloud Console are visable:
- Geocoding API
- Maps JavaScript API
- Places API

We installed:
- Web Google Maps
- CRM Maps
- Sales Maps
- Contacts Maps
- Website Google Address Form
- Web Google Maps Drawing
- Google Marker Icon Picker

The "Places API" has a masive number 3000 calls within 1hr (we only have 10 employees active). We expect the "Places API" is used for the autocomplete feature when typing partner's name or address.  Is is possible, that the API call is used when typing a letter?

G = 1st API call with 5 addresses = 5 API calls
Go = 2nd API call with 5 addresses = 10 API calls
Goo = 3rd call with 5 addresses = 15 API calls
Goog = 4th call with 5 addresses = 20 API calls
Googl = 6th call with 5 addresses = 25 API calls 
Google = 7nd call with 5 addresses = 30 API calls 

Or is there another cause which result in the same outcome?
Is it maybe caused when import Contacts?

Your feedback in this matter is higly appriciated.

Kind regards,
Michel

**Comment by gityopie** [comment]
hi @mlamie 

Thanks for reporting this issue.

> Is it possible, that the API call is used when typing a letter?

According to the documentation, a call is made for each keystroke 
https://developers.google.com/places/web-service/autocomplete#place_autocomplete_requests
and https://developers.google.com/maps/optimization-guide#places.

I have pushed a fixes to address this issue and also added some improvement such as specify fields to the autocomplete to avoid paying unused data https://developers.google.com/maps/documentation/javascript/places-autocomplete#get_place_information

**Comment by gityopie** [comment]
#121

**Comment by gityopie** [comment]
Hi @mlamie 

I already pushed the fixes for this issue on branch 12.0

I'll closed this one.
Feel free to open new issue if you found any other issue.
Thanks!
