### ISSUE TITLE
Error on click "View map" button

### ISSUE THREAD

**Issue by carlo-github** [gityopie/odoo-addons#124]
Odoo 12.0-20200116 (Community Edition)
Ubuntu 18.04

From the page of the Customer when I click on the button "View map", I got this error:

`Error:
Error: QWeb2: Template 'MapView.buttons' not found

http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:3374
Traceback:
exception@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:3374:7
_render@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:3419:103
render@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:3415:151
renderButtons@http://0.0.0.0:8069/web/content/2231-a5cf969/web.assets_backend.js:3441:1023
_renderControlPanelElements@http://0.0.0.0:8069/web/content/2231-a5cf969/web.assets_backend.js:1301:175
start@http://0.0.0.0:8069/web/content/2231-a5cf969/web.assets_backend.js:1293:1462
OdooClass.extend/</prototype[name]</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:3538:488
start@http://0.0.0.0:8069/web/content/2231-a5cf969/web.assets_backend.js:1558:1042
OdooClass.extend/</prototype[name]</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:3538:488
_widgetRenderAndInsert/<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:3684:52
then/</</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:681
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
add@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:797:471
then/</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:649
each@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:625:767
then/<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:560
Deferred@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:803:194
then@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:525
_widgetRenderAndInsert@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:3683:165
appendTo@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:3674:97
_startController@http://0.0.0.0:8069/web/content/2231-a5cf969/web.assets_backend.js:486:222
newController/<@http://0.0.0.0:8069/web/content/2231-a5cf969/web.assets_backend.js:511:13
then/</</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:681
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
fireWith@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:803:56
_createViewController/<@http://0.0.0.0:8069/web/content/2231-a5cf969/web.assets_backend.js:496:790
then/</</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:681
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
fireWith@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:801:202
then/</</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:874
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
fireWith@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:801:202
updateFunc/<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:804:491
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
fireWith@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:801:202
then/</</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:874
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
fireWith@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:801:202
then/</</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:874
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
fireWith@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:803:56
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
add@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:797:471
then/</</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:772
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
fireWith@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:801:202
then/</</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:874
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
fireWith@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:803:56
rpc/<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:3589:448
then/</</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:681
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
fireWith@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:803:56
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
fireWith@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:803:56
genericJsonRpc/<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:3558:10
then/</</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:681
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
fireWith@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:801:202
then/</</<@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:802:874
fire@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:796:299
fireWith@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:801:202
done@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:1192:95
callback@http://0.0.0.0:8069/web/content/1140-15b11ca/web.assets_common.js:1212:23`

**Comment by gityopie** [comment]
@carlo-github I'll check
could you also please check on your side if you install the correct module version match with your Odoo version?

**Comment by carlo-github** [comment]
From module info I obtain: 12.0.1.0.2 downloaded yesterday

**Comment by gityopie** [comment]
@carlo-github I don't have the issue on my side
on my local setup I used the latest commit of v12.0 [e0af40939a7](https://github.com/odoo/odoo/commit/e0af40939a719b381baaaa7e7dd66956222d9951)

have you try to restart your Odoo server?

**Comment by carlo-github** [comment]
@gityopie  I'm sorry for the late reply.. after I saw your video I tried again and the problem was that any my customer was geolocated by google API.. that causing the error reported.
Thank you.

**Comment by gityopie** [comment]
@carlo-github No problem, glad to heard it was fixed :)
