### ISSUE TITLE
V13 website_autocomplete

### ISSUE THREAD

**Issue by walkerblackwell** [gityopie/odoo-addons#135]
After removing api_multi there seems to be fairly little do to w/ migration to v13 but I do get this javascript error on website ecommerce address edit or add. Test odoo.sh instance:

Traceback:
TypeError: Cannot read property 'Autocomplete' of undefined
    at Class.initAutocomplete (https://inkjetmall-courses-2-1212481.dev.odoo.com/website_google_address_form/static/src/js/website_google_address_form.js:73:62)
    at https://inkjetmall-courses-2-1212481.dev.odoo.com/website_google_address_form/static/src/js/website_google_address_form.js:50:22

best,
Walker

**Comment by gityopie** [comment]
@walkerblackwell Actually I haven't try to migrate the module to v13 but if I check your instance looks like the library required `places` missing on the google map url
![Selection_308](https://user-images.githubusercontent.com/3539144/88004212-c27c0d80-cb30-11ea-9f6d-aadea137f202.png)

**Comment by walkerblackwell** [comment]
Thank you. I will figure out the fix.

Best regards,
Walker

**Comment by walkerblackwell** [comment]
Taking the template block from the v13 internal autocomplete and placing in the template block for website_ form module works. No console errors and autocomplete works.

best regards,
Walker
