### ISSUE TITLE
[12.0] Server error

### ISSUE THREAD

**Issue by FedericoLaTorre** [gityopie/odoo-addons#140]
I have this server error when I click map icon (I replace my domain with "mydomain")

Error:
Uncaught TypeError: Cannot read property 'equals' of undefined

https://mydomain/web/content/11447-8f5a76c/web.assets_backend.js:3767
Rastreo de error:
TypeError: Cannot read property 'equals' of undefined
    at https://mydomain/web/content/11447-8f5a76c/web.assets_backend.js:3767:244
    at Array.forEach (<anonymous>)
    at Class._clusterAddMarker (https://mydomain/web/content/11447-8f5a76c/web.assets_backend.js:3767:194)
    at Class._createMarker [as _super] (https://mydomain/web/content/11447-8f5a76c/web.assets_backend.js:3766:75)
    at Class._createMarker (https://mydomain/web/content/11447-8f5a76c/web.assets_backend.js:3847:722)
    at Class._createMarker (https://mydomain/web/content/11439-d372d28/web.assets_common.js:3541:371)
    at https://mydomain/web/content/11447-8f5a76c/web.assets_backend.js:3769:1934
    at Function.<anonymous> (https://mydomain/web/content/11439-d372d28/web.assets_common.js:12:558)
    at Class._renderUngrouped (https://mydomain/web/content/11447-8f5a76c/web.assets_backend.js:3769:1761)
    at Class._renderMarkers (https://mydomain/web/content/11447-8f5a76c/web.assets_backend.js:3769:941)

**Comment by FedericoLaTorre** [comment]
Hi, I modified like this

/**
         * Handle Multiple Markers present at the same coordinates
         */
        _clusterAddMarker: function (marker) {
            var markerInClusters = this.markerCluster.getMarkers();
            var existingRecords = [];
            if (markerInClusters.length > 0) {
                var position;
                markerInClusters.forEach(function (_cMarker) {
                    position = marker.getPosition();
                    if (position && position.equals(_cMarker.getPosition())) {
                        existingRecords.push(_cMarker._odooRecord);
                    }
                });
            }
            this.markerCluster.addMarker(marker);
            google.maps.event.addListener(
                marker,
                'click',
                this._markerInfoWindow.bind(this, marker, existingRecords)
            );
        },
        /**

And all the views dissapear from odoo. Am I modifyng right? Thanks for all the help! I'm new to odoo.

**Comment by gityopie** [comment]
@FedericoLaTorre yes, it looks correct.
What do you mean by "And all the views dissapear from odoo" ?

**Comment by FedericoLaTorre** [comment]
I mean that appart from the lateral menu of the theme, nothing else appear on screen, no list view, menus, nothing. And also no way to uninstall the module since there is no way to enter the apps menu.
I need to rename "map_renderer.js" so I can get the normal behavior again.

**Comment by gityopie** [comment]
Have you try to debug it?
if you are using Chrome browser, right click on any area on Odoo page and then choose `Inspect`or press `Ctrl + Shift + I` and then go to tab `Console`
After that, reload the page. I guess, there should be an error message or something informative there

Regarding the code modification, could you please double check if you put a `comma` after the method
```javascript
...
},
/**
* Handle Multiple Markers present at the same coordinates
*/
_clusterAddMarker: function (marker) {
    var markerInClusters = this.markerCluster.getMarkers();
    var existingRecords = [];
    if (markerInClusters.length > 0) {
        var position;
        markerInClusters.forEach(function (_cMarker) {
            position = marker.getPosition();
            if (position && position.equals(_cMarker.getPosition())) {
                existingRecords.push(_cMarker._odooRecord);
            }
        });
    }
    this.markerCluster.addMarker(marker);
    google.maps.event.addListener(
        marker,
        'click',
        this._markerInfoWindow.bind(this, marker, existingRecords)
    );
},
...
```

**Comment by FedericoLaTorre** [comment]
Well, without map_renderer.js it's not giving any errors and map is showing, it was a wrong api key. (thanks for the console tip).
If map_renderer.js is present, odoo interface won't load but console is not giving errors, some warnings about missing dependencies.

**Comment by FedericoLaTorre** [comment]
I also check for the commas and they are present.

**Comment by gityopie** [comment]
> Well, without map_renderer.js it's not giving any errors and map is showing, it was a wrong api key. (thanks for the console tip).
If map_renderer.js is present, odoo interface won't load but console is not giving errors, some warnings about missing dependencies.

Strange.. I'm not sure how did you setup the module, without `map_renderer.js` the module will caused an error and the Google map view will not working.

**Comment by FedericoLaTorre** [comment]
I first installed it, and then I remove the file. The chrome console shows that the file is missing, but it's working and so is the Odoo interface...

**Comment by gityopie** [comment]
It's really strange.. :thinking:

**Comment by gityopie** [comment]
Hi @FedericoLaTorre 

Please check the latest version of branch 12.0, the fixes has been applied there
I'll closed this one, if you still have an issue feel free to open a new one

Thank you
