### ISSUE TITLE
[13.0] Autocompletion not working on Google places and address

### ISSUE THREAD

**Issue by sergioeix** [gityopie/odoo-addons#148]
Hi Yopie i installed 13 branch and i am able to load maps but autocompletion its not working on Google places or address, i am getting this:
![image](https://user-images.githubusercontent.com/62206774/97095293-db2f1e80-165d-11eb-95fc-2ad55db359bc.png)
I am missing something?
Great Job Between
B/R

**Comment by gityopie** [comment]
Hi @sergioeix 

Can you confirmed the following API has been activated on your API Key?
- Geocoding API
- Maps JavaScript API
- Places API

Please also check if there is website restriction applied on it

**Comment by sergioeix** [comment]
There is no restriction and those 3 are activated, maps on contacts are
working well as views like contacts and crm
B/R

**Comment by sergioeix** [comment]
I can confirm that works like a charm, ty Yopi.
B/R Great Job
