### ISSUE TITLE
[14.0] web_google_maps: Sidebar not re-render

### ISSUE THREAD

**Issue by amirul-m** [gityopie/odoo-addons#172]
List in sidebar of google map view only render when I first open the menu

This is the list when I open view. It show only first 80 records
![image](https://user-images.githubusercontent.com/45891982/128446927-45c7031e-2091-45a0-9afa-4719fc066721.png)

Then I edit shown record to max (1-207), but the list is still the same
![image](https://user-images.githubusercontent.com/45891982/128447009-7da4c8a2-bf4b-4aae-a25b-e3dddeb2c5cb.png)

**Comment by amirul-m** [comment]
That means it's not re-render. Please help @gityopie . Thank you

**Comment by gityopie** [comment]
@amirul-m looks like your records aren't geolocalized yet.
can you make sure you set your latitude and longitude on your `google_map` view?
would be great if you can share your code

**Comment by amirul-m** [comment]
I have set partner_latitude and partner_longitude field on all records (207 record) to not zero value. this means I have geolocalize the records right? below is the proof.
![image](https://user-images.githubusercontent.com/45891982/128452163-2443d756-7c6e-4c4e-a4a9-a3f024b29e97.png)

Btw I'm using version 14.0.2.0.1 and I'm not custom the code based on this addons. I just install and use google map view on contacts (res partner) and realize I face this issue.

This is the last record on list view. record name **sfa**
![image](https://user-images.githubusercontent.com/45891982/128452702-147c38ec-bef1-4030-b1c1-3452ea4d3311.png)

But in google map view, the last record is **43**
![image](https://user-images.githubusercontent.com/45891982/128452656-c835e720-5d9f-4bb7-bf46-775c6633a8ce.png)
Which is that is the 80th record when I see on list view
![image](https://user-images.githubusercontent.com/45891982/128452688-7afe69e8-28cb-411d-be9a-f424a125ed73.png)

**Comment by gityopie** [comment]
@amirul-m Thank you 🙏
I've pushed the fixes
Do not hesitate to open new issue if you found one

**Comment by amirul-m** [comment]
Thank you so much 👍 I owe you. I'll check
