### ISSUE TITLE
add the map to custom model

### ISSUE THREAD

**Issue by donimuzur** [gityopie/odoo-addons#184]
hello
i want to  add map in custom model 
but i always get this error 
and i have add code, just like in your module in file res_partner.xml, is there any missing that i should change too?
sorry for my bad english

![image](https://user-images.githubusercontent.com/20512309/146118612-fa721785-7372-4de8-bc8f-bf959d3f0109.png)

`<record model="ir.ui.view" id="db_kios_view_map">
		<field name="name">db.kios.view.map</field>
		<field name="model">db.kios</field>
		<field name="arch" type="xml">
		 <map class="o_db_kios_map" library="geometry" string="Map" lat="partner_latitude" lng="partner_longitude" colors="green">
			<field name="kios_id"/>
				<field name="name"/>
				<field name="kios_address"/>
				<field name="city_name"/>
				<field name="kios_owner"/>
				<field name="kios_tlpn"/>
				<field name="kios_npwp"/>
				<field name="kios_namanpwp"/>
				<field name="kios_koordinat"/>
				<field name="kios_emp"/>
				<field name="kios_supervisor"/>
				<field name="partner_latitude"/>
				<field name="partner_longitude"/>
				<templates>
					<t t-name="kanban-box">
						<div class="oe_kanban_global_click o_kanban_record_has_image_fill o_res_partner_kanban">
							<img class="o_kanban_image" alt="Logo" t-att-src='_s + "/base/static/img/company_image.png"'/>
							<div class="oe_kanban_details">
								<strong class="o_kanban_record_title oe_partner_heading"><field name="name"/></strong>
								<div class="o_kanban_tags_section oe_kanban_partner_categories"/>
								<ul>
									<li><field name="kios_id"/></li>
									<li><field name="kios_address"/></li>
									<li><field name="city_name"/></li>
									<li><field name="kios_tlpn"/></li>
									<li class="o_text_overflow"><field name="kios_tlpn"/></li>
								</ul>
								<div class="oe_kanban_partner_links"/>
							</div>
						</div>
					</t>
				</templates>
			</map>
		</field>
	</record>
`
`<record id="action_db_kios_form_view3" model="ir.actions.act_window.view">
		<field eval="3" name="sequence"/>
		<field name="view_mode">map</field>
		<field name="view_id" ref="db_kios_view_map"/>
		<field name="act_window_id" ref="pg_marketing.db_kios_action"/>
	</record>`

**Comment by donimuzur** [comment]
im using odoo v12

**Comment by gityopie** [comment]
Hi @donimuzur 

Try change the attribute `colors` to `color` on your view.

```xml
<map class="o_db_kios_map" ... color="green">
```

`color` is for a fixed marker color
`colors` is for dynamic marker color

**Comment by donimuzur** [comment]
oh yeah my bad, in documentation you've already mention it

 thank you so much for your help,
