### ISSUE TITLE
Any plans to migrate this to 11.0

### ISSUE THREAD

**Issue by gdgellatly** [gityopie/odoo-addons#19]
I've tried, I can't make it work because I'm bad at js, but I've ported all the settings changes and mostly worked out the problems where the webclient has changed.

**Comment by gityopie** [comment]
Hello @gdgellatly 
Yes, the V11 are still in progress.
On V11, Odoo made a big changes on the JS side and seems like I have to start it again
everything need to re-write both view and the widgets.

**Comment by gdgellatly** [comment]
@gityopie Yes they are big changes, but I don't think it is entirely start again.  I will publish where I got to and link here later.  Just take the bits I did that you want.  

The settings file is perfect. 
The js loads but it doesn't work. Personally I wouldn't use it, but at least the new dependencies are in there.

**Comment by gityopie** [comment]
@gdgellatly Ok, thank you.
Yes, we need to re-write the JS files (`map` view and the widgets)

**Comment by beernaert** [comment]
I saw your addon and it look really great. I have just installed a fresh new odoo 11 on my server so if you need somebody to test it on odoo 11 please let me know.

**Comment by gityopie** [comment]
Hi @beernaert 

Thank you for your kindness :)
I can test it on my computer but..
it's way better to have one server test so anyone can test it.

The module itself are still on progress
Not all features has been migrated yet 
but for now the module is installable, `map` view has been migrated.

**Comment by bobslee** [comment]
Hi :)
Any plans for migration? When can we expect this?

**Comment by gityopie** [comment]
hi @bobslee 

The migrations is still on progress (sorry for very slow progress)
so far, the `map` view and two `widgets` has been migrated.
you can find it on this [branch](https://github.com/gityopie/odoo-addons/tree/v1120171028)

**Comment by adriencombourieu** [comment]
@gityopie 
Just installed on v11. Thank you very much this is awesome!

**Comment by gityopie** [comment]
Hi @adriencombourieu 

Thanks for reporting the issue
I have fixed it

**Comment by davidogles** [comment]
Thanks for the app.  I have it running flawlessly on a v10 CE install.  I just download this for the v11.  Installed on my laptop running Odoo v11 CE on Windows 7 professional and all works OK.  Installed on my server (ubuntu 16.04 Odoo 11 CE) and no errors, but does not display anything, just a blank form.  Website_google_maps is installed and running.

**Comment by soheiloo** [comment]
i install it but how could it work?

**Comment by soheiloo** [comment]
it dowsont show me
if any body can help me send telegram message to me i give him access 
please
00447937002798

**Comment by gityopie** [comment]
hi @soheiloo 

Please watch this [video](https://www.youtube.com/watch?v=2UdG5ILDtiY&feature=youtu.be)
It could be working fine without Google API Keys but my suggestion is better to set it up

to setup Google API Keys you can find it [here](https://developers.google.com/maps/documentation/javascript/get-api-key)

Here screenshot list of APIs enabled for my dev
![screenshot from 2017-08-31 17-26-31](https://user-images.githubusercontent.com/3539144/37523085-783f6784-2958-11e8-8d37-b41cffa01acf.png)

**Comment by adriencombourieu** [comment]
@gityopie 
I notice that when the partner form is opened in a "new" window (eg when creating a partner from a crm.lead) the widget does not work properly : the list of address does not display. It seems to be a pure front end issue. Tested on firefox.

**Comment by gityopie** [comment]
@adriencombourieu 
it was an old issue related to bootstrap modal  https://github.com/twbs/bootstrap/issues/4160
I'm quite surprised this issue is still exists on V11
anyway, I've pushed the fixes [commit ID](https://github.com/gityopie/odoo-addons/commit/1a3da17518ed0e16a0120e2dfc0301a9fefd4737)

Thanks for reporting this issue :)

**Comment by adriencombourieu** [comment]
It now wors thanks

**Comment by gustavovalverde** [comment]
Hi @gityopie. What kind of help do you need here?

I could upload a fork to Odoo.sh to have it up to date, running with Odoo Unit Testing, and it would work as a publci platform so people can test the module functionalities. If you're interested let me know. 

Also, is there anything in the JS that you need for the autocomplete? We made a module that also makes auto-completion in real time but with a local government webservice, maybe someone of the team who work that can help you to finalize the migration to v11.

**Comment by gustavovalverde** [comment]
Maybe this snippet of the code they made could give you some ideas (not sure as you're implementation seems more advanced)
https://github.com/odoo-dominicana/l10n-dominicana/commit/04e04d3439ad327c6d2d0687c2d41c54ccf74254

**Comment by gityopie** [comment]
Hi @gustavovalverde 

Yes, I'm interested
That's a very good idea actually
The more people recognize this module, the more people could interested to improve it or maybe add a new feature.

For the migrations to V11
so far, the `map` view and two widgets `Address form autocomplete` and `Places autocomplete` has been migrated, the route features are still in progress.
you can find the development branch [here](https://github.com/gityopie/odoo-addons/tree/v1120171028)

Please let us know if you have manage to add this module on Odoo.sh

Thank you

**Comment by soheiloo** [comment]
Hi my dear friend,

Sea’s of thanks for your guidance,


I just download and install your last GitHub link , It is such a great ….

And dear my friend do you know how can I command from terminal to update my broken module ,that caused my server not load?

$ odoo.py -d db_name -u module_name
 Is this work for you?

For more relation I  enthusiast to have your contact phone and give you access if you pleases,

Sinceared,

Soheil shamshiri,

**Comment by gityopie** [comment]
Hi @soheiloo 

If you have a problem/issue related to the module, please create a new one.

> Hi my dear friend,
> 
> Sea’s of thanks for your guidance,
> 
> 
> I just download and install your last GitHub link , It is such a great ….
> 
> And dear my friend do you know how can I command from terminal to update my broken module ,that caused my server not load?
> 
> $ odoo.py -d db_name -u module_name
>  Is this work for you?
> 
> For more relation I  enthusiast to have your contact phone and give you access if you pleases,
> 
> Sinceared,
> 
> Soheil shamshiri,
> 
> 
> From: Yopi Angi
> Sent: Thursday, April 5, 2018 11:14 AM
> To: gityopie/odoo-addons
> Cc: soheiloo; Mention
> Subject: Re: [gityopie/odoo-addons] Any plans to migrate this to 11.0 (#19)
> 
> Hi @gustavovalverde
> Yes, I'm interested
> That's a very good idea actually
> The more people recognize this module, the more people could interested to improve it or maybe add a new feature.
> For the migrations to V11
> so far, the map view and two widgets Address form autocomplete and Places autocomplete has been migrated, the route features are still in progress.
> you can find the development branch here
> Please let us know if you have manage to add this module on Odoo.sh
> Thank you
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

This issue is for migration discussion

Thank you

**Comment by soheiloo** [comment]
Hi my dear friend,

I state my gratitude for your very effort, 
Please inform me even routing function is complete,



Regards,

**Comment by soheiloo** [comment]
Hi friends

I don't know it cause all my servers and businesses down with this error

http://www.foorooshi.com/web/content/446-2c47af3/web.assets_common.js:3689
Traceback:
Error: QWeb2: Template 'MapView' not found
    at Object.exception (http://www.foorooshi.com/web/content/446-2c47af3/web.assets_common.js:3689:7)
    at Engine._render (http://www.foorooshi.com/web/content/446-2c47af3/web.assets_common.js:3734:103)
    at Engine.render (http://www.foorooshi.com/web/content/446-2c47af3/web.assets_common.js:3730:151)
    at Class.renderElement (http://www.foorooshi.com/web/content/446-2c47af3/web.assets_common.js:3943:1078)
    at http://www.foorooshi.com/web/content/446-2c47af3/web.assets_common.js:3943:917
    at http://www.foorooshi.com/web/content/446-2c47af3/web.assets_common.js:802:681
    at fire (http://www.foorooshi.com/web/content/446-2c47af3/web.assets_common.js:796:299)
    at Object.add [as done] (http://www.foorooshi.com/web/content/446-2c47af3/web.assets_common.js:797:467)
    at Array.<anonymous> (http://www.foorooshi.com/web/content/446-2c47af3/web.assets_common.js:802:649)
    at Function.each (http://www.foorooshi.com/web/content/446-2c47af3/web.assets_common.js:625:767)


if you can help me debbug and run my service please contact me,

cheers,

**Comment by soheiloo** [comment]
first it was good but then ...
