### ISSUE TITLE
Odoo 16 modules

### ISSUE THREAD

**Issue by CasVissers-360ERP** [gityopie/odoo-addons#207]
Hi,

Any plans to migrate the modules to v16?

Kind regards,
Cas

**Comment by gityopie** [comment]
Hi @CasVissers-360ERP 

Yes, the migration is in progress

The bad news is I won't make them open anymore, the repository will be in private.
I have plans to charge for access to the repository.

**Comment by CasVissers-360ERP** [comment]
Ok, let me know. We are willing to pay for the modules.

**Comment by gityopie** [comment]
Hi @CasVissers-360ERP 

The codebase will be published on this repository https://github.com/mithnusa

I haven't find way for the payment and how much the price will be
I will keep you posted

**Comment by gityopie** [comment]
Hi, I've update the information on this repository https://github.com/mithnusa
