### ISSUE TITLE
Display field datetime on map: can not convert to user timezone.

### ISSUE THREAD

**Issue by FaTaToo** [gityopie/odoo-addons#21]
Hi @gdgellatly,
Thank for your fantasy work.
I would like to display some datetime information on map. However, it just displays datetime in UTC timezone.
Do you have any idea about this issue?
Thanks,

**Comment by gityopie** [comment]
Hi @FaTaToo 

Can you please take the latest version?

I've checked and it's working fine
here are the screenshots
![screen shot 2018-01-16 at 9 19 01 pm](https://user-images.githubusercontent.com/3539144/34993469-02ad1fb2-fb03-11e7-8306-2d878af9c4c6.png)

on marker info window,
![screen shot 2018-01-16 at 9 16 30 pm](https://user-images.githubusercontent.com/3539144/34993482-0b7dcf1a-fb03-11e7-9c88-d3fedb3498eb.png)

Thanks
