### ISSUE TITLE
Autofill not working pop-up from - Odoo 16.0

### ISSUE THREAD

**Issue by TimGlimmerveen-360ERP** [gityopie/odoo-addons#213]
Module: contacts_gautocomplete_address_form

After quick creating a res.partner on sale.order or crm.lead the autofill isn't working in the pop-up form.

There seems to be no google autofill in the window at all.

**Comment by gityopie** [comment]
Thanks for the report
I will check it

**Comment by gityopie** [comment]
Hi @TimGlimmerveen-360ERP 
I've pushed the fixes on the branch 16.0

Could you please take a look?

For a quick check, you can check on the demo instance 
http://35.209.158.83:8069/
guest | guest

Thank you!

**Comment by netfxtech** [comment]
Will you publish the 16.0 branch like you've done for the other branches? I don't see it in the list. 

Thank you

**Comment by steven-bouillon** [comment]
Will you publish the 16.0 branch like you've done for the other branches? I don't see it in the list.

Thank you

**Comment by gityopie** [comment]
Hi @netfxtech 
No, sorry :|
The modules was hosted on this repository https://github.com/mithnusa but it's private

**Comment by TimGlimmerveen-360ERP** [comment]
Hi @gityopie 
It works:)

**Comment by gityopie** [comment]
@TimGlimmerveen-360ERP Glad to hear that
I will close this issue
Do not hesitate to open a new one if you find another issue
Thank you!
