### ISSUE TITLE
the automatic name search in company and the automatic address search in the Address field that does not work

### ISSUE THREAD

**Issue by Damien74000** [gityopie/odoo-addons#32]
With Simple Backend Theme

*** Odoo 10.0 community

**Comment by Damien74000** [comment]
auto-searching address(gplaces_address_form), name not working with google map ,odoo-10

**Comment by gityopie** [comment]
hi @Damien74000,

what do you mean by name search in company?
I guess, you don't need to apply the widget if it's a relation field to `res.company`

would be great if you can provide error message

**Comment by Damien74000** [comment]
That the problem of configuring google map api

**Comment by Damien74000** [comment]
thank you

**Comment by gityopie** [comment]
Great!
Thanks @Damien74000
