### ISSUE TITLE
Error: QWeb2: Template 'web_google_maps.FieldGooglePlaces' not found

### ISSUE THREAD

**Issue by tituxx** [gityopie/odoo-addons#34]
Im getting above error when gpoing to client view after installed  web_google_map addon.
Odoo 9.0
thanks for your help!

http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:2444
Rastreo de error:
exception@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:2444:7
_render@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:2482:92
render@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:2478:146
renderElement@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:2632:1068
renderElement@http://192.99.243.41/web/content/570-e4f4e3c/web.assets_backend.js:3643:2957
SoftwareClass.extend/</prototype[name]</<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:2539:556
renderElement@http://192.99.243.41/web/content/570-e4f4e3c/web.assets_backend.js:3649:1323
SoftwareClass.extend/</prototype[name]</<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:2539:556
__widgetRenderAndInsert/<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:2632:912
then/</</<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:678
fire@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:644:281
add@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:645:467
then/</<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:631
each@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:473:758
then/<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:553
Deferred@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:651:189
then@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:518
__widgetRenderAndInsert@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:2632:879
replace@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:2632:718
init_fields/<@http://192.99.243.41/web/content/570-e4f4e3c/web.assets_backend.js:3607:616
_.forEach@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:12:558
init_fields@http://192.99.243.41/web/content/570-e4f4e3c/web.assets_backend.js:3607:570
load_record/<@http://192.99.243.41/web/content/570-e4f4e3c/web.assets_backend.js:3549:24
then/</</<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:678
fire@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:644:281
add@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:645:467
then/</<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:631
each@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:473:758
then/<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:553
Deferred@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:651:189
then@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:518
load_record@http://192.99.243.41/web/content/570-e4f4e3c/web.assets_backend.js:3548:360
trigger@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:2620:166
trigger@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:2622:636
do_show/shown</<@http://192.99.243.41/web/content/570-e4f4e3c/web.assets_backend.js:3546:185
then/</</<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:678
fire@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:644:281
fireWith@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:649:198
then/</</<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:849
fire@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:644:281
fireWith@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:649:198
then/</</<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:849
fire@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:644:281
fireWith@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:649:198
Deferred/</deferred[tuple[0]]@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:651:31
fire@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:644:281
fireWith@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:649:198
then/</</<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:849
fire@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:644:281
fireWith@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:649:198
then/</</<@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:650:849
fire@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:644:281
fireWith@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:649:198
done@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:1040:86
callback@http://192.99.243.41/web/content/557-f1782d0/web.assets_common.js:1060:15

**Comment by gityopie** [comment]
Hi @tituxx,

I could not reproduce the error
on my test I'm using the latest commit of Odoo v9.0 [83d2dd5521a](https://github.com/odoo/odoo/commit/83d2dd5521a7cf77cf2d08568621808cdc9851e9)

**Comment by tituxx** [comment]
Thanks, updating fixed the error!
ᐧ

2018-07-03 9:42 GMT-03:00 Yopi Angi <notifications@github.com>:

**Comment by gityopie** [comment]
Ok, no prob
