### ISSUE TITLE
11.0 Geolocation now only working on Address widget, not Places.

### ISSUE THREAD

**Issue by gdgellatly** [gityopie/odoo-addons#54]
To reproduce is easy.  
Click Create and select partner-assignation tab
Just create a partner and enter a place say Buckingham Palace in the name field
Lat long doesn't change
Do same in street field it does.
I added 
`<attribute name="options">{'lat': 'partner_latitude', 'lng': 'partner_longitude'}</attribute>` to the name field in the res_partner view and this resolved it, but not sure if it is right.

**Comment by gityopie** [comment]
#55
