### ISSUE TITLE
Error when create contact

### ISSUE THREAD

**Issue by qvinh222** [gityopie/odoo-addons#80]
Odoo community, V12. Fresh new database.
I try to create new contact, and following error occur. I can't not add new contact.

Uncaught TypeError: self.places_autocomplete.setBounds is not a function
http://localhost:8069/web/content/543-15b8d3f/web.assets_backend.js:3264
Traceback:
TypeError: self.places_autocomplete.setBounds is not a function
    at http://localhost:8069/web/content/543-15b8d3f/web.assets_backend.js:3264:361

**Comment by gityopie** [comment]
hi @qvinh222 

Thanks for report this issue
Yes, you are right when user allow the browser to identify his location the error appears

I'll try look into this issue

**Comment by gityopie** [comment]
Hi @qvinh222 

I have created a PR #81
if you have time, could you please check if it solved this issue?

Thank you

**Comment by gityopie** [comment]
hi @qvinh222 ,

I have merged the fixes into the main branch, so I will close this issue.
Don't hesitate to open a new issue if you find a new one.

Thank you
