### ISSUE TITLE
Kanban Box on mobile devices displays incorrectly 

### ISSUE THREAD

**Issue by intellego-rbn** [gityopie/odoo-addons#86]
Hi, great work on these Google Maps addons! We absolutely love them!

We have just on issue: when displayed in a mobile device (iOS on Safari, Google Chrome and the Odoo iOS app), when you select a contact on the map the Kanban box shows no content, just the X to close the box. Google places, on the other hand do display correctly. 

We would be glad to assist in any way we can! 

Regards

**Comment by gityopie** [comment]
Hi @intellego-rbn 

Thanks!
I've pushed some update to fix this issue
could you please check?  [12.0-dev](https://github.com/gityopie/odoo-addons/tree/12.0-dev)

please let me know if it's solved the issue or not :)

**Comment by intellego-rbn** [comment]
Solved! Great work! Thanks
