### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by katyukha** [gityopie/odoo-addons#87]
Hello! 

First of all thank you for your work!

I have the question about license of these addons. As i [see](https://github.com/gityopie/odoo-addons/issues/49) you had some troubles publishing addons under LGPL license and now they are under AGPL (but LICENSE file in the repository root still contains LGPL license). Is it the only trouble that prevents you to publish these addons under LGPL license? If so, than it could be fixed by using `LGPL-3` license code in manifest ([see](https://github.com/odoo/odoo/blob/5e055a2afd23bd4e6a29c18c86d1978dcd98fc9f/odoo/addons/base/models/ir_module.py#L278)).

Thanks!

**Comment by gityopie** [comment]
Hello @katyukha 

Thank you!
Actually, my issue publish the module on Odoo apps has solved
you can check on the Odoo apps, there is an option for Odoo version
<img width="435" alt="screen shot 2018-12-22 at 20 39 50" src="https://user-images.githubusercontent.com/3539144/50374494-1dcedc80-062a-11e9-99e3-b4f99ba7859e.png">

**Comment by katyukha** [comment]
Thank you for response
