### ISSUE TITLE
Address format

### ISSUE THREAD

**Issue by hmrickhoff** [gityopie/odoo-addons#94]
address is formated wrong in street field

"Number" "Street" 

in Germany we write the address "Street" "Number"

possible to change that?

**Comment by gityopie** [comment]
@hmrickhoff yes, it's possible 
the address format can be changed
you can check here https://github.com/gityopie/odoo-addons/blob/12.0/sale_maps/views/res_partner.xml#L19

**Comment by hmrickhoff** [comment]
thanks a lot, works like a charm!
