### ISSUE TITLE
Google error - provide autocomplete feature when typing partner's name - V11

### ISSUE THREAD

**Issue by thiago95macedo** [gityopie/odoo-addons#98]
When I am registering a new contact / partner I get this error below:

![image](https://user-images.githubusercontent.com/40434859/55089485-dcfcbe80-5083-11e9-903d-7ae3ffccf8b1.png)

**Comment by gityopie** [comment]
@thiago95macedo have enter your Google API key in map settings ? (General Settings)
In your API key, please enable the following APIs & Services:
- Geocoding API
- Maps JavaScript API
- Places API

**Comment by thiago95macedo** [comment]
@gityopie     
Yes brother!

![image](https://user-images.githubusercontent.com/40434859/55270132-e481ba80-5271-11e9-9780-4b43e0a40bc8.png)

**Comment by thiago95macedo** [comment]
I updated some more modules and it worked, my installation is old, since the beginning of 2018 ... so I update the code unless it is necessary
